# Generated by Django 5.2 on 2025-06-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prototype',
            new_name='Importer',
        ),
    ]
